### ISSUE TITLE
Static analisys

### ISSUE THREAD

**Issue by g00fer** [lukaszfok/Driver-GSM#11]
Check your code with cppcheck (sourceforge).

**Comment by lukaszfok** [comment]
Checking .metadata/.plugins/org.eclipse.cdt.make.core/specs.c...
1/4 files checked 25% done
Checking .metadata/.plugins/org.eclipse.cdt.make.core/specs.cpp...
2/4 files checked 50% done
Checking gsm.c...
3/4 files checked 75% done
Checking portopen.c...
4/4 files checked 100% done

**Comment by g00fer** [comment]
cppcheck command:
cppcheck . --enable=all

2016-11-22 15:57 GMT+01:00 lukaszfok notifications@github.com:

**Comment by lukaszfok** [comment]
Checking .metadata/.plugins/org.eclipse.cdt.make.core/specs.c...
1/4 files checked 25% done
Checking .metadata/.plugins/org.eclipse.cdt.make.core/specs.cpp...
2/4 files checked 50% done
Checking gsm.c...
3/4 files checked 75% done
Checking portopen.c...
4/4 files checked 100% done
(information) Cppcheck cannot find all the include files (use --check-config for details)

witch cppcheck . --enable=all
